### ISSUE TITLE
Error in enre_java_1.0.4.jar

### ISSUE THREAD

**Issue by DeWuwo** [xjtu-enre/ENRE-java#25]
# Error
## scene
Run base using enre_java_1.0.4.jar
After entities and deps identfied successfully
## error info
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 912482
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at util.SingleCollect.getEntityById(SingleCollect.java:98)
        at visitor.deper.ReflectBf.setDep(ReflectBf.java:40)
        at client.IdentifyRelations.run(IdentifyRelations.java:51)
        at client.TemplateWork.workflow(TemplateWork.java:52)
        at client.Main.main(Main.java:24)

**Comment by Lynn-Dai** [comment]
The exception is caused by the reflection of external class and invoking its provided methods. Please download the 1.0.5 version later, it solves this exception.
